assert_lefthook_installed = true

[[pre-commit.jobs]]
name = "deadnix"
glob = "*.nix"
run = "deadnix --fail {staged_files}"

[[pre-commit.jobs]]
name = "editorconfig-checker"
run = "editorconfig-checker -exclude LICENSE"

[[pre-commit.jobs]]
name = "statix"
run = "statix check --format errfmt"

[[pre-commit.jobs]]
name = "taplo"
glob = "*.toml"
run = "taplo lint {staged_files}"

[[pre-commit.jobs]]
interactive = true
name = "treefmt"
run = "treefmt"
stage_fixed = true
