excludes = [".envrc", "*.lock", ".gitignore"]
on-unmatched = "warn"

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]
